FROM node:20-alpine

WORKDIR /frontend

COPY package.json ./
COPY yarn.lock ./

RUN yarn install && \
    yarn cache clean

COPY . .

EXPOSE 8080

RUN yarn build

CMD ["yarn", "preview", "--host", "0.0.0.0"]
