FROM node:20-alpine AS builder
WORKDIR /frontend
COPY package.json yarn.lock ./
RUN yarn install

COPY . .

FROM node:20-alpine AS runner
WORKDIR /frontend
COPY --from=builder /frontend .

EXPOSE 8080
CMD ["sh", "-c", "yarn build && node .output/server/index.mjs"]