FROM node:20.19.1-alpine

WORKDIR /frontend

COPY package.json ./

RUN yarn install && \
    yarn add esbuild@0.25.4 --dev --exact && \
    yarn cache clean

COPY . .

ENV API_BASE_URL=http://localhost:3000
ENV API_SECRET=ticetmp
ENV NODE_ENV=development
ENV PORT=8080
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=8080

EXPOSE 8080

CMD ["npx", "nuxi", "dev", "--host", "0.0.0.0"]