services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    env_file: "backend.env"
    depends_on:
      - postgres
      - example
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
      - "5173:5173"
    env_file: "frontend.env"
    depends_on:
      - backend
    restart: always

  example:
    build:
      context: ./example
      dockerfile: Dockerfile.example
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=development
    restart: always

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=owasp_scanner
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  zap:
    build:
      context: .
      dockerfile: Dockerfile.zap
    ports:
      - "9000:9000"
    environment:
      - ZAP_API_KEY=thiskeyforzapbyticetmp
    restart: always

volumes:
  postgres-data:
