name: Code Deploy only

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to server with rsync
      uses: contention/rsync-deployments@v2.0.0
      with:
        USER: ${{ secrets.SSH_USER }}
        HOST: ${{ secrets.SSH_IP }}
        DEPLOY_KEY:  ${{ secrets.SSH_KEY }}
        LOCALPATH: ./
        REMOTEPATH: ${{ secrets.SSH_PATH }}
