name: Code Deploy only

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to server with rsync
      uses: contention/rsync-deployments@v2.0.0
      env:
        REMOTE_USER: ${{ secrets.SSH_USER }}
        REMOTE_HOST: ${{ secrets.SSH_IP }}
        REMOTE_PATH: ${{ secrets.SSH_PATH }}
      with:
        USER: $REMOTE_USER
        HOST: $REMOTE_HOST
        LOCALPATH: ./
        REMOTEPATH: $REMOTE_PATH
