name: Code Deploy only

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to server with rsync
      env:
        REMOTE_USER: ${{ secrets.SSH_USER }}
        REMOTE_PASS: ${{ secrets.SSH_PASS }}
        REMOTE_HOST: ${{ secrets.SSH_IP }}
        REMOTE_PATH: ${{ secrets.SSH_PATH }}
      run: |
        sshpass -p "$SSH_PASSWORD" rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
