name: Deploy & rerun all container (except db)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build by compose
      uses: D3rHase/ssh-command-action@v0.3.1
      with:
        host: ${{ secrets.SSH_IP }}
        user: ${{ secrets.SSH_USER }}
        private_key: ${{ secrets.SSH_KEY }}
        command: 'cd ${{ secrets.SSH_PATH }} && docker compose up -d --force-recreate --build backend frontend example zap'
